<?php

namespace Database\Seeders;
use App\Models\Negara;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class NegaraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['name' => 'AFGHANISTAN'],
            ['name' => 'ALBANIA'],
            ['name' => 'ALGERIA'],
            ['name' => 'ANGOLA'],
            ['name' => 'ANGUILLA'],
            ['name' => 'ANTIGUA'],
            ['name' => 'ARGENTINA'],
            ['name' => 'AUSTRALIA'],
            ['name' => 'AUSTRIA'],
            ['name' => 'ARMENIA'],
            ['name' => 'AZERBAIJAN'],
            ['name' => 'AMERICAN SAMOA'],
            ['name' => 'ANDORRA'],
            ['name' => 'BAHAMAS'],
            ['name' => 'BAHRAIN'],
            ['name' => 'BANGLADESH'],
            ['name' => 'BARBADOS'],
            ['name' => 'BELGIUM'],
            ['name' => 'BERMUDA'],
            ['name' => 'BHUTAN'],
            ['name' => 'BOLIVIA'],
            ['name' => 'BOTSWANA'],
            ['name' => 'BRAZIL'],
            ['name' => 'BRUNEI'],
            ['name' => 'BULGARIA'],
            ['name' => 'BURUNDI'],
            ['name' => 'BENIN'],
            ['name' => 'BELARUS'],
            ['name' => 'BELIZE'],
            ['name' => 'BOSNIA AND HERZEGOVINA'],
            ['name' => 'BULKINA FASO'],
            ['name' => 'CAMEROON'],
            ['name' => 'CANADA'],

            ['name' => 'CHILE'],
            ['name' => 'CHINA'],
            ['name' => 'COLOMBIA'],
            ['name' => 'COSTA RICA'],
            ['name' => 'CZECH'],
            ['name' => 'CROATIA'],
            ['name' => 'CAMBODIA'],
            ['name' => 'CENTRAL AFRICAN REPUBLIC'],
            ['name' => 'CYPRUS'],
            ['name' => 'CASTRIES'],
            ['name' => 'DENMARK'],
            ['name' => 'DOMINICA'],
            ['name' => 'EGYPT'],
            ['name' => 'EL SALVADOR'],
            ['name' => 'ETHIOPIA'],
            ['name' => 'ERITREA'],
            ['name' => 'ESTONIA'],
            ['name' => 'FIJI'],
            ['name' => 'FINLAND'],
            ['name' => 'FRANCE'],
            ['name' => 'FRENCH POLYNESIA'],
            ['name' => 'GABON'],
            ['name' => 'GUAM'],
            ['name' => 'GERMANY'],
            ['name' => 'GHANA'],
            ['name' => 'GIBRALTAR'],
            ['name' => 'GREECE'],
            ['name' => 'GRENADA'],
            ['name' => 'GUATEMALA'],

            ['name' => 'GUINEA'],
            ['name' => 'GUYANA'],
            ['name' => 'GAMBIA'],
            ['name' => 'GEORGIA'],
            ['name' => 'HONG KONG'],
            ['name' => 'HUNGARY'],
            ['name' => 'ICELAND'],
            ['name' => 'INDIA'],
            ['name' => 'INDONESIA'],
            ['name' => 'IRAN'],
            ['name' => 'IRAQ'],
            ['name' => 'IRELAND REP.'],
            ['name' => 'ITALY'],
            
            ['name' => 'COTE D IVOIRE'],
            ['name' => 'JAMAICA'],
            ['name' => 'JAPAN'],
            ['name' => 'JORDAN'],
            ['name' => 'KENYA'],
            ['name' => 'NORTH KOREA'],
            ['name' => 'SOUTH KOREA'],
            ['name' => 'KUWAIT'],
            ['name' => 'KAZAKHSTAN'],
            ['name' => 'LAOS'],
            ['name' => 'LEBANON'],
            ['name' => 'LESOTHO'],
            ['name' => 'LIBERIA'],
            ['name' => 'LIBYA'],
            ['name' => 'LIECHTENSTEIN'],
            ['name' => 'LUXEMBOURG'],
            ['name' => 'LATVIA'],
            ['name' => 'LITHUANIA'],
            ['name' => 'MALAWI'],
            ['name' => 'MALAYSIA'],
            ['name' => 'MALI'],
            ['name' => 'MALTA'],
            ['name' => 'MAURITANIA'],
            ['name' => 'MAURITIUS'],
            ['name' => 'MEXICO'],
            ['name' => 'MONACO'],
            ['name' => 'MONGOLIA'],
            ['name' => 'MONTSERRAT'],
            ['name' => 'MOROCCO'],
            ['name' => 'MOZAMBIQUE'],
            ['name' => 'MADAGASCAR'],
            ['name' => 'MOLDOVA'],
            ['name' => 'MYANMAR'],
            ['name' => 'MUSCAT'],
            ['name' => 'MACAU'],
            ['name' => 'MACEDONIA'],
            ['name' => 'MAYOTTE'],
            ['name' => 'MARSHALL ISLAND'],
            ['name' => 'MICRONESIA FEDERATION'],
            ['name' => 'MONTENEGRO'],
            ['name' => 'NAURU'],
            ['name' => 'NEPAL'],
            ['name' => 'NETHERLANDS'],
            ['name' => 'NEW ZEALAND'],
            ['name' => 'NICARAGUA'],
            ['name' => 'NIGER'],
            ['name' => 'NIGERIA'],
            ['name' => 'NORWAY'],
            ['name' => 'NAMIBIA'],
            ['name' => 'NEW CALEDONIA'],
            ['name' => 'NETHERLANDS ANTILLES'],
            ['name' => 'NORTHERN MARIANA ISLANDS'],
            ['name' => 'OMAN'],
            ['name' => 'PAKISTAN'],
            ['name' => 'PANAMA'],
            ['name' => 'PAPUA N GUINEA'],
            ['name' => 'PARAGUAY'],
            ['name' => 'PERU'],
            ['name' => 'PHILIPPINES'],
            ['name' => 'POLAND'],
            ['name' => 'PORTUGAL'],
            ['name' => 'PACIFIC ISLAND'],
            ['name' => 'PUERTO RICO'],
            ['name' => 'PALESTINE'],
            ['name' => 'PALAU'],
            ['name' => 'QATAR'],
            ['name' => 'ROMANIA'],
            ['name' => 'RWANDA'],
            ['name' => 'RUSSIA'],
            ['name' => 'SAMOA'],
            ['name' => 'SAN MARINO'],
            ['name' => 'SAUDI ARABIA'],
            ['name' => 'SENEGAL'],
            ['name' => 'SIERRA LEONE'],
            ['name' => 'SINGAPORE'],
            ['name' => 'SOUTH AFRICA'],
            ['name' => 'SOMALIA'],
            ['name' => 'SPAIN'],
            ['name' => 'SRI LANKA'],
            ['name' => 'SUDAN'],
            ['name' => 'SWEDEN'],
            ['name' => 'SWITZERLAND'],
            ['name' => 'SYRIA'],
            ['name' => 'SOLOMON ISLAND'],
            ['name' => 'SLOVENIA'],
            ['name' => 'SLOVAKIA, REP'],
            ['name' => 'SURINAME'],
            ['name' => 'SWAZILAND'],
            ['name' => 'SAO TOME & PRINCIPE'],
            ['name' => 'SERBIA AND MONTENEGRO'],
            ['name' => 'ST. LUCIA'],
            ['name' => 'SOUTH GEORGIA & SOUTH SANDWICH ISLAND'],
            ['name' => 'SERBIA'],
            ['name' => 'ST. VINCENT AND THE GRENADINES'],
            ['name' => 'SOUTH SUDAN'],
            ['name' => 'SAINT KITTS AND NEVIS'],
            ['name' => 'TAHITI'],
            ['name' => 'TAIWAN'],
            ['name' => 'TANZANIA'],
            ['name' => 'TURKMENISTAN'],
            ['name' => 'THAILAND'],
            ['name' => 'TOBAGO'],
            ['name' => 'TOGO'],
            ['name' => 'TONGA'],
            ['name' => 'TRINIDAD'],
            ['name' => 'TUNISIA'],
            ['name' => 'TURKEY'],
            ['name' => 'TAJIKISTAN'],
            ['name' => 'TUVALU'],
            ['name' => 'UGANDA'],
            ['name' => 'UNITED KINGDOM'],
            ['name' => 'U.S.A'],
            ['name' => 'URUGUAY'],
            ['name' => 'U.A.E'],
            ['name' => 'UKRAINE'],
            ['name' => 'UZBEKISTAN'],
            ['name' => 'VENEZUELA'],
            ['name' => 'VIETNAM'],
            ['name' => 'VANUATU'],
            ['name' => 'YEMEN ARAB REP'],
            ['name' => 'YUGOSLAVIA'],
            ['name' => 'ZAIRE'],
            ['name' => 'ZAMBIA'],
            ['name' => 'ZIMBABWE'],
        ];

        Negara::insert($data);
    }
}
